---
deployment:
  tasks:
    - rm -rf /home/pigworldsmart/crm-build
    - mkdir -p /home/pigworldsmart/crm-build
    - unzip -q -o /home/pigworldsmart/crm.pigworldsmart.com/dist.zip -d /home/pigworldsmart/crm-build
    - cp -R /home/pigworldsmart/crm-build/dist/. /home/pigworldsmart/crm.pigworldsmart.com/