function InboxView({ messages, onRefresh, onReply }) {
  return <section className="panel-card communication-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Communication inbox</div><h2>Messages from the farm app</h2></div><button className="filter-button" type="button" onClick={onRefresh}>Refresh</button></div>{messages.length === 0 ? <div className="state-message">No messages from farm users yet.</div> : <div className="communication-message-list">{messages.map((message) => <article className="communication-message-row" key={message.id}><div><strong>{message.sender_name || "Farm member"}</strong><small>{message.sender_email || ""} · {new Date(message.created_at).toLocaleString()}</small></div><p>{message.message}</p>{onReply && <button className="ghost-button" type="button" onClick={() => onReply(message)}>Reply</button>}</article>)}</div>}</section>;
}

function BroadcastView({ staff, messages, notification, setNotification, onSubmit, canNotify }) {
  if (!canNotify) return <section className="panel-card communication-workspace-panel"><div className="eyebrow">Broadcast</div><h2>Read-only communication access</h2><p className="communication-muted">Your role can read communication messages but cannot send broadcasts.</p></section>;
  return <section className="panel-card communication-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Broadcast</div><h2>Send a notification</h2></div><span>Farm-wide or targeted</span></div><form className="communication-composer" onSubmit={onSubmit}><select value={notification.recipient_id} onChange={(event) => setNotification((current) => ({ ...current, recipient_id: event.target.value }))}><option value="">Everyone in this farm</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.name} ({member.crm_role || member.role})</option>)}{messages.filter((message) => message.sender_id && !staff.some((member) => String(member.id) === String(message.sender_id))).map((message) => <option key={`app-${message.sender_id}`} value={message.sender_id}>{message.sender_name || message.sender_email || "Farm member"} (app user)</option>)}</select><textarea required rows="5" value={notification.message} onChange={(event) => setNotification((current) => ({ ...current, message: event.target.value }))} placeholder="Write a notification message" /><button className="primary-button" type="submit">Send notification</button></form></section>;
}

function ActivityView({ selected, interactions, canReply }) {
  return <section className="panel-card communication-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Customer activity</div><h2>{selected ? `${selected.name} timeline` : "Customer communication"}</h2></div><span>{selected ? "Selected from Customers" : "No customer selected"}</span></div>{!selected ? <div className="state-message">Select a customer in the Customers workspace to review communication activity.</div> : interactions.length === 0 ? <div className="state-message">No customer activity recorded yet.</div> : <div className="timeline">{interactions.map((item) => <div className="timeline-item" key={item.id || `${item.type}-${item.occurred_at}`}><span className="timeline-icon">{item.type === "call" ? "⌕" : item.type === "email" ? "@" : "✦"}</span><div><strong>{item.type[0].toUpperCase() + item.type.slice(1)}</strong><span>{item.notes || "No notes added"}</span></div><time>{new Date(item.occurred_at).toLocaleString()}</time></div>)}</div>}{selected && !canReply && <p className="communication-muted">Your role can review activity but cannot add customer replies.</p>}</section>;
}

function TemplatesView({ templates, onUse, hasCustomer }) {
  return <section className="panel-card communication-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Quick actions</div><h2>Communication templates</h2></div><span>Save a customer follow-up</span></div>{!hasCustomer && <div className="state-message">Select a customer in the Customers workspace before using a template.</div>}<div className="automation-grid">{templates.map((template) => <button key={template.label} type="button" className="automation-card" disabled={!hasCustomer} onClick={() => onUse(template)}><strong>{template.label}</strong><span>{template.copy}</span></button>)}</div></section>;
}

export function CommunicationWorkspace({ view, messages, staff, notification, setNotification, onSubmit, onRefresh, onReply, selected, interactions, templates, onUseTemplate, canNotify, canReply, canRead }) {
  if (!canRead) return <section className="panel-card communication-workspace-panel"><div className="eyebrow">Communication</div><h2>Access restricted</h2><p className="communication-muted">Your role does not have access to CRM communication.</p></section>;
  if (view === "communication-broadcast") return <BroadcastView staff={staff} messages={messages} notification={notification} setNotification={setNotification} onSubmit={onSubmit} canNotify={canNotify} />;
  if (view === "communication-activity") return <ActivityView selected={selected} interactions={interactions} canReply={canReply} />;
  if (view === "communication-templates") return <TemplatesView templates={templates} onUse={onUseTemplate} hasCustomer={Boolean(selected)} />;
  return <InboxView messages={messages} onRefresh={onRefresh} onReply={canNotify ? onReply : null} />;
}
