import { FinanceDashboard } from "./FinanceDashboard";

function SubscriptionRows({ subscriptions }) {
  if (subscriptions.length === 0) return <div className="state-message">No farm subscription records are available yet.</div>;
  return <div className="finance-record-list">{subscriptions.map((farm) => <article className="finance-record-row" key={farm.id}><div><strong>{farm.name}</strong><span>{farm.mother_pig_count ?? 0} mother pigs</span></div><span>{farm.subscription_plan || "No plan"}</span><span>{farm.payment_amount ? `${farm.payment_amount} ${farm.payment_currency}` : "No payment"}</span><span className={`payment-status ${farm.payment_status === "paid" ? "paid" : "pending"}`}>{farm.payment_status || "pending"}</span></article>)}</div>;
}

function PlansView({ plans, planForm, setPlanForm, savePlan, togglePlan, canManagePlans }) {
  return <section className="panel-card finance-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Billing catalog</div><h2>Subscription plans</h2></div><span>{plans.length} plans</span></div>{canManagePlans && <form className="finance-plan-form" onSubmit={savePlan}><input required value={planForm.code} onChange={(event) => setPlanForm((current) => ({ ...current, code: event.target.value }))} placeholder="Code" /><input required value={planForm.name} onChange={(event) => setPlanForm((current) => ({ ...current, name: event.target.value }))} placeholder="Plan name" /><input required type="number" min="0" step="0.01" value={planForm.amount} onChange={(event) => setPlanForm((current) => ({ ...current, amount: event.target.value }))} placeholder="Amount" /><input required maxLength="3" value={planForm.currency} onChange={(event) => setPlanForm((current) => ({ ...current, currency: event.target.value.toUpperCase() }))} placeholder="Currency" /><input type="number" min="1" value={planForm.pig_limit} onChange={(event) => setPlanForm((current) => ({ ...current, pig_limit: event.target.value }))} placeholder="Pig limit" /><button className="primary-button" type="submit">Add plan</button></form>}{plans.length === 0 ? <div className="state-message">No subscription plans have been created.</div> : <div className="finance-record-list">{plans.map((plan) => <article className="finance-record-row" key={plan.id}><div><strong>{plan.name}</strong><span>{plan.code}</span></div><span>{plan.amount} {plan.currency}</span><span>{plan.pig_limit ? `Up to ${plan.pig_limit} pigs` : "Unlimited pigs"}</span><span>{plan.active ? "Active" : "Retired"}</span>{canManagePlans && <button className="filter-button" type="button" onClick={() => togglePlan(plan)}>{plan.active ? "Retire" : "Activate"}</button>}</article>)}</div>}</section>;
}

function ReportingView({ report }) {
  const status = report?.by_status || {};
  return <section className="panel-card finance-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Revenue reporting</div><h2>Financial performance</h2></div><span>{report?.generated_at ? new Date(report.generated_at).toLocaleDateString() : "No report date"}</span></div><div className="finance-report-grid"><div><span>Active relationships</span><strong>{report?.active_relationships ?? 0}</strong><small>CRM relationships excluding lost records</small></div><div><span>Qualified pipeline</span><strong>{report?.qualified ?? 0}</strong><small>Relationships ready for follow-up</small></div><div><span>Conversion rate</span><strong>{report?.conversion_rate ?? 0}%</strong><small>Won relationships in the report</small></div></div><div className="finance-report-status"><strong>Pipeline status counts</strong>{Object.entries(status).map(([key, value]) => <span key={key}>{key}: {value}</span>)}</div><p className="finance-disclaimer">This report combines CRM pipeline indicators with subscription data. It does not represent a complete transaction ledger.</p></section>;
}

export function FinanceWorkspace({ view, customers, counts, report, calculator, setCalculator, projectedRevenue, plans, planForm, setPlanForm, savePlan, togglePlan, canManagePlans, statuses }) {
  if (view === "finance-subscriptions") return <section className="panel-card finance-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Farm subscriptions</div><h2>Subscription status</h2></div><span>{report?.subscriptions?.length || 0} farms</span></div><SubscriptionRows subscriptions={report?.subscriptions || []} /></section>;
  if (view === "finance-payments") return <section className="panel-card finance-workspace-panel"><div className="panel-heading"><div><div className="eyebrow">Payment activity</div><h2>Latest payment activity</h2></div><span>Latest payment per farm</span></div><SubscriptionRows subscriptions={report?.subscriptions || []} /><p className="finance-disclaimer">Payment activity currently shows the latest payment returned by the finance report API. A full transaction history requires a dedicated payment-history endpoint.</p></section>;
  if (view === "finance-plans") return <PlansView plans={plans} planForm={planForm} setPlanForm={setPlanForm} savePlan={savePlan} togglePlan={togglePlan} canManagePlans={canManagePlans} />;
  if (view === "finance-reporting") return <ReportingView report={report} />;
  return <FinanceDashboard customers={customers} counts={counts} report={report} calculator={calculator} setCalculator={setCalculator} projectedRevenue={projectedRevenue} plans={plans} planForm={planForm} setPlanForm={setPlanForm} savePlan={savePlan} togglePlan={togglePlan} canManagePlans={canManagePlans} statuses={statuses} />;
}
