import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1';
const TOKEN_KEY = 'pigyworld_access_token';
const api = axios.create({ baseURL: API_BASE_URL });
api.interceptors.request.use((config) => {
  const token = localStorage.getItem(TOKEN_KEY);
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});
const emptyCustomer = { farm_id: '1', name: '', email: '', phone: '', company: '', address: '', type: 'lead', status: 'new', notes: '' };
const statuses = ['all', 'new', 'contacted', 'qualified', 'won', 'lost'];
const interactionTypes = ['call', 'email', 'visit', 'meeting', 'note'];

function App() {
  const [customers, setCustomers] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [interactions, setInteractions] = useState([]);
  const [filters, setFilters] = useState({ search: '', status: 'all' });
  const [form, setForm] = useState(emptyCustomer);
  const [interaction, setInteraction] = useState({ type: 'call', notes: '' });
  const [editing, setEditing] = useState(false);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState(null);
  const [auth, setAuth] = useState({ email: '', password: '', token: localStorage.getItem(TOKEN_KEY) || '' });
  const selected = useMemo(() => customers.find((customer) => customer.id === selectedId) || null, [customers, selectedId]);
  const counts = useMemo(() => statuses.slice(1).reduce((result, status) => ({ ...result, [status]: customers.filter((customer) => customer.status === status).length }), {}), [customers]);
  const showNotice = (message, tone = 'info') => { setNotice({ message, tone }); window.setTimeout(() => setNotice(null), 3500); };

  const loadCustomers = async () => {
    try {
      setLoading(true);
      const params = { ...(filters.search ? { search: filters.search } : {}), ...(filters.status !== 'all' ? { status: filters.status } : {}) };
      const response = await api.get('/crm/customers', { params });
      const data = response.data?.data || [];
      setCustomers(data);
      setSelectedId((current) => data.some((customer) => customer.id === current) ? current : data[0]?.id || null);
    } catch (error) { showNotice(error.response?.data?.message || 'Unable to load customers. Check your connection.', 'error'); }
    finally { setLoading(false); }
  };
  useEffect(() => { if (auth.token) loadCustomers(); }, [auth.token, filters.status]);
  useEffect(() => {
    if (!selected) { setInteractions([]); return; }
    api.get(`/crm/customers/${selected.id}/interactions`).then((response) => setInteractions(response.data?.data || [])).catch(() => showNotice('Unable to load interaction history.', 'error'));
  }, [selectedId]);

  const login = async (event) => { event.preventDefault(); try { const response = await api.post('/auth/login', { email: auth.email, password: auth.password }); const token = response.data.access_token; localStorage.setItem(TOKEN_KEY, token); setAuth((current) => ({ ...current, token })); showNotice('Welcome back.'); } catch (error) { showNotice(error.response?.data?.message || 'Authentication failed. Check your credentials.', 'error'); } };
  const updateForm = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const saveCustomer = async (event) => {
    event.preventDefault(); if (!form.name.trim()) return showNotice('A customer name is required.', 'error');
    try { setSaving(true); const payload = { ...form, farm_id: Number(form.farm_id) }; const response = editing ? await api.put(`/crm/customers/${selected.id}`, payload) : await api.post('/crm/customers', payload); const saved = response.data.data; setCustomers((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setSelectedId(saved.id); setForm(emptyCustomer); setEditing(false); showNotice(editing ? 'Customer updated.' : 'Customer added.', 'success'); }
    catch (error) { showNotice(error.response?.data?.message || 'Could not save this customer.', 'error'); } finally { setSaving(false); }
  };
  const startEditing = () => { setForm({ ...emptyCustomer, ...selected }); setEditing(true); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const deleteCustomer = async () => { if (!selected || !window.confirm(`Delete ${selected.name}? This also removes interaction history.`)) return; try { await api.delete(`/crm/customers/${selected.id}`); setCustomers((current) => current.filter((item) => item.id !== selected.id)); setSelectedId(null); showNotice('Customer deleted.', 'success'); } catch (error) { showNotice(error.response?.data?.message || 'Could not delete this customer.', 'error'); } };
  const addInteraction = async (event) => { event.preventDefault(); if (!selected) return; try { const response = await api.post(`/crm/customers/${selected.id}/interactions`, { ...interaction, occurred_at: new Date().toISOString() }); setInteractions((current) => [response.data.data, ...current]); setInteraction({ type: 'call', notes: '' }); showNotice('Interaction logged.', 'success'); } catch (error) { showNotice(error.response?.data?.message || 'Could not log interaction.', 'error'); } };

  if (!auth.token) return <Login auth={auth} setAuth={setAuth} onSubmit={login} notice={notice} />;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand-block"><div className="brand-mark">P</div><div><strong>Pigyworld</strong><span>Customer desk</span></div></div><nav className="side-nav"><button className="nav-item active"><span>◈</span> Customers</button><button className="nav-item" onClick={() => showNotice('Reports are coming soon.') }><span>⌁</span> Reports</button></nav><div className="side-caption">Pipeline</div><div className="pipeline-list">{statuses.slice(1).map((status) => <button key={status} onClick={() => setFilters((current) => ({ ...current, status }))}><span className={`status-dot ${status}`} />{status[0].toUpperCase() + status.slice(1)}<b>{counts[status] || 0}</b></button>)}</div><div className="sidebar-footer"><span className="avatar">PW</span><div><strong>Workspace</strong><small>Farm operations</small></div><button className="icon-button" title="Sign out" onClick={() => { localStorage.removeItem(TOKEN_KEY); setAuth((current) => ({ ...current, token: '' })); }}>↪</button></div></aside>
    <main className="main-panel"><header className="topbar"><div><div className="eyebrow">Relationship management</div><h1>Customers</h1></div><div className="top-actions"><button className="ghost-button" onClick={loadCustomers}>↻ Refresh</button><button className="primary-button" onClick={() => { setEditing(false); setForm(emptyCustomer); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>＋ Add customer</button></div></header>{notice && <div className={`notice ${notice.tone}`}>{notice.message}</div>}<section className="stats-row"><div><span>Total relationships</span><strong>{customers.length}</strong></div><div><span>Qualified leads</span><strong>{counts.qualified || 0}</strong></div><div><span>Won this cycle</span><strong>{counts.won || 0}</strong></div><div className="accent-stat"><span>Conversion focus</span><strong>{customers.length ? `${Math.round(((counts.won || 0) / customers.length) * 100)}%` : '0%'}</strong></div></section>
      <section className="workspace-grid"><div className="list-panel panel-card"><div className="panel-heading"><div><h2>Customer list</h2><span>{customers.length} records in view</span></div><button className="filter-button" onClick={() => setFilters({ search: '', status: 'all' })}>Clear filters</button></div><div className="search-field"><span>⌕</span><input value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} onKeyDown={(event) => event.key === 'Enter' && loadCustomers()} placeholder="Search name, company, or email" /></div><div className="filter-tabs">{statuses.map((status) => <button key={status} className={filters.status === status ? 'selected' : ''} onClick={() => setFilters((current) => ({ ...current, status }))}>{status === 'all' ? 'All' : status}</button>)}</div><div className="customer-list">{loading ? <div className="state-message">Loading customers…</div> : customers.length === 0 ? <div className="state-message">No customers match these filters.</div> : customers.map((customer) => <button key={customer.id} className={`customer-row ${selectedId === customer.id ? 'selected' : ''}`} onClick={() => setSelectedId(customer.id)}><span className="customer-avatar">{customer.name.slice(0, 1).toUpperCase()}</span><span className="customer-row-copy"><strong>{customer.name}</strong><small>{customer.company || customer.email || 'No company details'}</small></span><span className={`status-label ${customer.status}`}>{customer.status}</span><span className="row-arrow">›</span></button>)}</div></div>
        <div className="detail-column">{editing ? <CustomerForm form={form} updateForm={updateForm} onSubmit={saveCustomer} onCancel={() => setEditing(false)} saving={saving} /> : selected ? <><section className="detail-card panel-card"><div className="detail-header"><div className="profile-heading"><span className="profile-avatar">{selected.name.slice(0, 1).toUpperCase()}</span><div><div className="eyebrow">{selected.type} relationship</div><h2>{selected.name}</h2><span>{selected.company || 'Independent contact'}</span></div></div><div className="detail-actions"><button className="ghost-button" onClick={startEditing}>Edit</button><button className="danger-button" onClick={deleteCustomer}>Delete</button></div></div><div className="contact-grid"><ContactItem label="Email" value={selected.email} /><ContactItem label="Phone" value={selected.phone} /><ContactItem label="Address" value={selected.address} /><ContactItem label="Status" value={selected.status} accent /></div>{selected.notes && <div className="notes"><span>Notes</span><p>{selected.notes}</p></div>}</section><section className="activity-card panel-card"><div className="panel-heading"><div><h2>Activity timeline</h2><span>Keep every conversation in context</span></div><span className="activity-count">{interactions.length} events</span></div><form className="interaction-composer" onSubmit={addInteraction}><select value={interaction.type} onChange={(event) => setInteraction((current) => ({ ...current, type: event.target.value }))}>{interactionTypes.map((type) => <option key={type} value={type}>{type[0].toUpperCase() + type.slice(1)}</option>)}</select><input value={interaction.notes} onChange={(event) => setInteraction((current) => ({ ...current, notes: event.target.value }))} placeholder="Add a note about this interaction…" /><button className="primary-button" type="submit">Log activity</button></form><div className="timeline">{interactions.length === 0 ? <div className="state-message">No activity recorded yet.</div> : interactions.map((item) => <div className="timeline-item" key={item.id}><span className="timeline-icon">{item.type === 'call' ? '⌕' : item.type === 'email' ? '@' : '✦'}</span><div><strong>{item.type[0].toUpperCase() + item.type.slice(1)}</strong><span>{item.notes || 'No notes added'}</span></div><time>{new Date(item.occurred_at).toLocaleDateString()}</time></div>)}</div></section></> : <div className="empty-detail panel-card"><span>◈</span><h2>Choose a relationship</h2><p>Select a customer from the list to see their details and activity.</p></div>}</div></section></main>
  </div>;
}

function Login({ auth, setAuth, onSubmit, notice }) { return <div className="login-screen"><div className="login-art"><div className="art-label">PIGYWORLD / CRM</div><div className="art-copy"><h1>Better conversations.<br /><em>Stronger herds.</em></h1><p>Keep buyers, partners, and opportunities moving with the farm.</p></div><div className="art-footer">Customer relationships, thoughtfully managed.</div></div><form className="login-card" onSubmit={onSubmit}><div className="brand-block"><div className="brand-mark">P</div><div><strong>Pigyworld</strong><span>Customer desk</span></div></div><div><div className="eyebrow">Welcome back</div><h2>Sign in to your workspace</h2><p className="muted-copy">Use your Pigyworld account to continue.</p></div>{notice && <div className={`notice ${notice.tone}`}>{notice.message}</div>}<label>Email address<input type="email" required value={auth.email} onChange={(event) => setAuth((current) => ({ ...current, email: event.target.value }))} placeholder="you@example.com" /></label><label>Password<input type="password" required value={auth.password} onChange={(event) => setAuth((current) => ({ ...current, password: event.target.value }))} placeholder="Your password" /></label><button className="primary-button" type="submit">Continue <span>→</span></button><small className="login-help">Protected by your Pigyworld account</small></form></div>; }
function CustomerForm({ form, updateForm, onSubmit, onCancel, saving }) { return <section className="form-card panel-card"><div className="panel-heading"><div><div className="eyebrow">{form.id ? 'Update record' : 'New relationship'}</div><h2>{form.id ? 'Edit customer' : 'Add a customer'}</h2></div><button className="icon-button" onClick={onCancel} title="Close">×</button></div><form className="customer-form" onSubmit={onSubmit}><label>Full name<input required value={form.name} onChange={(event) => updateForm('name', event.target.value)} placeholder="e.g. Amara Foods" /></label><div className="form-two"><label>Email<input type="email" value={form.email} onChange={(event) => updateForm('email', event.target.value)} placeholder="contact@company.com" /></label><label>Phone<input value={form.phone} onChange={(event) => updateForm('phone', event.target.value)} placeholder="+254 700 000 000" /></label></div><div className="form-two"><label>Company<input value={form.company} onChange={(event) => updateForm('company', event.target.value)} placeholder="Business or organization" /></label><label>Relationship<select value={form.type} onChange={(event) => updateForm('type', event.target.value)}><option value="lead">Lead</option><option value="buyer">Buyer</option><option value="supplier">Supplier</option></select></label></div><div className="form-two"><label>Status<select value={form.status} onChange={(event) => updateForm('status', event.target.value)}>{statuses.slice(1).map((status) => <option key={status} value={status}>{status[0].toUpperCase() + status.slice(1)}</option>)}</select></label><label>Farm ID<input value={form.farm_id} onChange={(event) => updateForm('farm_id', event.target.value)} /></label></div><label>Address<input value={form.address} onChange={(event) => updateForm('address', event.target.value)} placeholder="Location or postal address" /></label><label>Notes<textarea rows="4" value={form.notes} onChange={(event) => updateForm('notes', event.target.value)} placeholder="Context, preferences, or next steps" /></label><div className="form-actions"><button className="ghost-button" type="button" onClick={onCancel}>Cancel</button><button className="primary-button" type="submit" disabled={saving}>{saving ? 'Saving…' : form.id ? 'Save changes' : 'Create customer'}</button></div></form></section>; }
function ContactItem({ label, value, accent }) { return <div className="contact-item"><span>{label}</span><strong className={accent ? `status-label ${value}` : ''}>{value || 'Not provided'}</strong></div>; }
export default App;
